### ISSUE TITLE
Rancher 1.2 Support

### ISSUE THREAD

**Issue by Rucknar** [infinityworksltd/prometheus-rancher-exporter#11]
Rancher 1.2 contains some API changes, it also contains a new API V2 that should allow us to get better data out, easier. The existing version doesn't work with 1.2, i've got a re-written exporter i'm working on right now, hopefully when that's ready it should give us support of the V2 API.

**Comment by metalmatze** [comment]
Hopefully this is a complete rewrite in Go? 😊

**Comment by Rucknar** [comment]
It is indeed :) It's nearly functionally complete now, i'm just handling some additional host state, then i've got some testing to do. I'm fairly new to Go, open to feedback once i've pushed V1.  It should offer much better granularity of health status, though it may require updates to some existing queries.

**Comment by metalmatze** [comment]
Happy to hear that. Just ping me if there's something to review. I'm happy to help!

**Comment by Rucknar** [comment]
@metalmatze Right... branch pushed (rewrite) https://github.com/infinityworksltd/prometheus-rancher-exporter/tree/rewrite

Image available here: infinityworks/prometheus-rancher-exporter:go-rewrite

You can run locally with: 

```
docker run -d -e CATTLE_ACCESS_KEY="XXXXXXXX" -e CATTLE_SECRET_KEY="XXXXXXX" -e CATTLE_URL="http://<YOUR_IP>:8080/v2-beta/" -p 9010:9010 infinityworks/prometheus-rancher-exporter:go-rewrite
```

Thoughts / Feedback welcome. The metrics for health are way more detailed now. I'll get some example queries up tomorrow and work on the docs tomorrow afternoon.

**Comment by Rucknar** [comment]
Update...

Tracking a backwards compatibility issue with the v1 API, it seems rancher still issue this as the default API in 1.2. Though it looks fixable, i'll get an update out today to resolve. As a result, you might see the stack results not come through when using the V1 API.

**Comment by metalmatze** [comment]
I reviewed the rewrite yesterday quickly. Overall really good code. Can't complain!
You might want to look into `fmt.Printf` though. You build a lot of strings yourself.
On the weekend I might be able to fetch the code and do a test run and a proper review. 😊

**Comment by Rucknar** [comment]
Update Numero 2...

I've updated the code to resolve some missing states for stacks and services. 

Agree @metalmatze I wanted to get a basic version up ASAP so people can monitor their kit, that's my next planned change, i've found where to pull the states from the API too so should be able to future-proof it somewhat.

Latest tag: go-rewrite2
Branch Updated.

pls use with v2-beta API for now.

**Comment by Rucknar** [comment]
V1 API support should now work in the new code, it auto-detects the API version and adjusts the pages it hits now.

Latest tag: go-rewrite3
Branch Updated.

**Comment by metalmatze** [comment]
The metrics are looking **REALLY** good! Awesome! 🎉 

Only thing that annoys me a bit is the repeated `_state_` in every metrics, which can be safely removed. It's all state after all anyway! 😊 

`host_state_...`
`stack_state...`
`stack_state_...`

I think one can create pretty awesome dashboards with all those metrics! 🎈

**Comment by Rucknar** [comment]
Cool :) 

Agree on the state bits, I'll tidy it up. Once tested a bit more I'll update the docs with some example queries. 

Next up is tackling the repetition

**Comment by metalmatze** [comment]
I run the exporter now in my cluster for 24h and it just crashed...
```
12/11/2016 2:03:41 PMError Collecting JSON from API:  Get http://127.0.0.1:8000/v1/services/: dial tcp 127.0.0.1:8000: connect: cannot assign requested address
12/11/2016 2:03:41 PMpanic: Get http://127.0.0.1:8000/v1/services/: dial tcp 127.0.0.1:8000: connect: cannot assign requested address
12/11/2016 2:03:41 PM
12/11/2016 2:03:41 PMgoroutine 197632 [running]:
12/11/2016 2:03:41 PMpanic(0x850080, 0xc8454e8360)
12/11/2016 2:03:41 PM	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
12/11/2016 2:03:41 PMgithub.com/infinityworksltd/prometheus-rancher-exporter/services.getJSONservices(0xc8454e8210, 0x27, 0xc820012012, 0x14, 0xc820016012, 0x28, 0x0, 0x0, 0x0, 0x0, ...)
12/11/2016 2:03:41 PM	/go/src/github.com/infinityworksltd/prometheus-rancher-exporter/services/services.go:210 +0x2fc
12/11/2016 2:03:41 PMgithub.com/infinityworksltd/prometheus-rancher-exporter/services.(*Exporter).serviceScrape(0xc8200e80e0, 0xc82001206b, 0x1d, 0xc820012012, 0x14, 0xc820016012, 0x28, 0xc845520060, 0x0, 0x0)
12/11/2016 2:03:41 PM	/go/src/github.com/infinityworksltd/prometheus-rancher-exporter/services/services.go:238 +0x456
12/11/2016 2:03:41 PMgithub.com/infinityworksltd/prometheus-rancher-exporter/services.(*Exporter).Collect(0xc8200e80e0, 0xc845520060)
12/11/2016 2:03:41 PM	/go/src/github.com/infinityworksltd/prometheus-rancher-exporter/services/services.go:334 +0xdf
12/11/2016 2:03:41 PMgithub.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc8455f8040, 0xc845520060, 0x7fd40327e990, 0xc8200e80e0)
12/11/2016 2:03:41 PM	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:382 +0x58
12/11/2016 2:03:41 PMcreated by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
12/11/2016 2:03:41 PM	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x360
12/11/2016 2:03:46 PMStarting Prometheus Exporter for Rancher. Listen Address:  :9010 metricsPath:  /metrics rancherURL:  http://127.0.0.1:8000/v1 AccessKey:  XXX
12/11/2016 2:03:46 PMINFO[0000] Starting Server: :9010                        file="rancher_exporter.go" line=60
```
Not really sure what happened there.

**Comment by Rucknar** [comment]
@metalmatze I'm not sure on that one to be honest. I've just pushed `:rewrite`, hopefully a final version. I've tidied the code up, the docs and pushed it through a fair bit of testing on 1.2. I'll probably merge into master this evening.

**Comment by metalmatze** [comment]
I think all of the metrics still have `_state_` in the metrics, right?

**Comment by Rucknar** [comment]
They do indeed, i'm hoping to expose more of the information through the API in the coming weeks. If i drop `rancher_host_state_removing` to be just `rancher_host_removing` it makes it harder to add more in depth info later. I envisage metrics such as `rancher_host_hardware_cpus` for instance.

**Comment by Rucknar** [comment]
@metalmatze Another option of course, is to denote the state as a label, instead of a unique metric in it's own right. `host_state: name=X state=X` It would require much less code.

**Comment by Rucknar** [comment]
Okay, ignore the last message above. It works really well and is really neat... but it's broken Prometheus and seems to be against the design.

**Comment by Rucknar** [comment]
Hi All,

I ran the output of the metrics by one of the Prometheus core engineers, they correctly pointed out the correct way to get the 'state' dimension is through labels. I've updated the code and pushed. Apologies if anyone's already built some queries against the metric names i pushed yesterday. Hopefully these will now stay stable. On the plus side, it's now much easier and faster to correctly query the data from tools like grafana.

I'm going to close this ticket down for now, if we see any issues with the new codebase, please raise them as separate tickets and i'll look to resolve them ASAP.
