### ISSUE TITLE
Service health status and simple status isn't being populated in Grafana

### ISSUE THREAD

**Issue by inabhi9** [infinityworksltd/prometheus-rancher-exporter#20]
For eg,
This query `rancher_service_health_status{health_state="unhealthy"} == 1` in grafana doesn't load anything while it works fine in prometheus

Nevermind, it's silly mistake of time range selection

**Comment by Rucknar** [comment]
Glad you got it sorted @inabhi9 . I always make sure grafana is set to read the 'current' value as well, rather than the default 'average'
