### ISSUE TITLE
incorrect state

### ISSUE THREAD

**Issue by acscloud** [infinityworksltd/prometheus-rancher-exporter#21]
From dashboard or prometheus:
![rancherstate](https://cloud.githubusercontent.com/assets/27944860/25372260/47253584-29c7-11e7-976e-4e39bf4d3499.jpg)

From Rancher UI:
![acturestate](https://cloud.githubusercontent.com/assets/27944860/25372302/74bc27be-29c7-11e7-9606-432aa376b50d.jpg)

Seems all of the state is healthy.

Rancher version: 1.5.5

**Comment by Rucknar** [comment]
I presume this is from a Kubernetes deployment? What version of the exporter are you running?
Could you send a full print out of the `/metrics` endpoint for the exporter?

**Comment by Rucknar** [comment]
Just noticed, on the above it seems it's only the system services that aren't showing as good.

First thing to check here is if the Exporter is set to hide system services, this is controlled with the `HIDE_SYS` environment variable. It's set to true in recent deployments, set that to false and see if it resolves.

Failing that, It would be useful to get that output, plus the query being used for one of the failing critical boxes shown above.

**Comment by hiscal2015** [comment]
@Rucknar 
HIDE_SYS has been already set to false (exporter version v0.22.52):
```
docker run -d -e CATTLE_URL="http://rancher-server:8080/v2-beta" -e CATTLE_ACCESS_KEY="XXXX" -e CATTLE_SECRET_KEY="XXXX" -e HIDE_SYS=false --restart=always --link=rancher-server --name=rancher_exporter -p 9173:9173 XXX/rancher-exporter:v0.22.52
```

Here's the metrics (do not open with notepad):

[metrics.txt](https://github.com/infinityworksltd/prometheus-rancher-exporter/files/960183/metrics.txt)

**Comment by Rucknar** [comment]
I'll take a look at the logs today, might be nothing but the command you've pasted has `HIDE_SYS=false` it should be `HIDE_SYS="false" as the environment variable must always be of type string. I noticed this because my colleague had the exact problem with another service just yesterday!

**Comment by hiscal2015** [comment]
@Rucknar Still no luck.

![rancherexporterissue](https://cloud.githubusercontent.com/assets/15604715/25510422/905bc4b6-2bf2-11e7-82a9-57fb7ea6a000.jpg)

Here's the log:
```
 time="2017-04-28T01:05:46Z" level=info msg="Starting Prometheus Exporter for Rancher" 
 time="2017-04-28T01:05:46Z" level=info msg="Runtime Configuration in-use: URL of Rancher Server: http://rancher-server:8080/v2-beta AccessKey: XXXXXSystem Services hidden: false" 
 time="2017-04-28T01:05:46Z" level=info msg="Starting Server on port :9173 and path /metrics" 
 time="2017-04-28T01:05:50Z" level=info msg="Scraping: http://rancher-server:8080/v2-beta/stacks/" 
 time="2017-04-28T01:05:50Z" level=info msg="Metrics successfully processed for stacks" 
 time="2017-04-28T01:05:50Z" level=info msg="Scraping: http://rancher-server:8080/v2-beta/services/" 
 time="2017-04-28T01:05:50Z" level=info msg="Metrics successfully processed for services" 
```

**Comment by Rucknar** [comment]
@hiscal2015 Apologies, lost track of this one. Just looking at the above, do the stacks in-question have any status being picked up? Could you provide a screenshot of the query `rancher_stack_health_status{name="healthcheck"}`

**Comment by hiscal2015** [comment]
@Rucknar 
![rancherexporterissue1](https://cloud.githubusercontent.com/assets/15604715/26040179/746735b8-3955-11e7-9461-77f5a69c9d59.jpg)

**Comment by Rucknar** [comment]
@hiscal2015 Looking at that screenshot, i can see the second result for that stack as coming back healthy... which seems to contradict the `rancher_stack_health_status{name="$stack", health_state="healthy"}` query you posted above.

I'm wondering if the variable substitution in Grafana is to blame here. In grafana, there should be a settings menu, under that there should be a templates option. Could you post a screenshot for the settings of the `$stack` query?

As a quick test, you could create a new singlestat plugin and paste in the query without substitution...

`rancher_stack_health_status{name="healthcheck", health_state="healthy"}` for instance.

**Comment by hiscal2015** [comment]
@Rucknar I recently upgraded rancher from 1.5.5 to 1.5.9, healthcheck state is fine now, but still have incorrect status on "scheduler" and "etcd"

![rancher1](https://cloud.githubusercontent.com/assets/15604715/26141076/9e907e36-3b0c-11e7-920c-efc2b41029be.jpg)

![rancher2](https://cloud.githubusercontent.com/assets/15604715/26141079/a3897514-3b0c-11e7-940c-c4372eef085e.jpg)

**Comment by hiscal2015** [comment]
@Rucknar I realized there's no scheduler component in Kubernetes environment, and what's the etcd service here? Is it available in defualt Kubernetes environment?

**Comment by Rucknar** [comment]
@hiscal2015 That would explain it then. I'm not sure on the kubernetes specifics. It seems the exporter in this case is working as expected. It might be worth taking a look at the raw output, comparing it with ranchers GUI and choosing the services you wish to monitor.
