### ISSUE TITLE
Feature Request - Improved Health Status Codes

### ISSUE THREAD

**Issue by Rucknar** [infinityworksltd/prometheus-rancher-exporter#3]
The Rancher API should be exposing a number of different health status's now, e.g.
- Active
- Upgrading
- Degraded

Currently, we only report on things being either Active (=1) or something else (=0). We need to update our logic to take these into account. Potentially also need 'inactive and 'reconnecting' for the hosts, although that needs checking in the API.

**Comment by JamesBarwell** [comment]
Looks like the different states are here: https://github.com/rancher/cattle/blob/fe3a25a7d46f6ed9cfd70c5c39c98dca0e4af083/code/iaas/model/src/main/java/io/cattle/platform/core/constants/CommonStatesConstants.java

``` java
    public static final String CREATED = "created";
    public static final String CREATING = "creating";
    public static final String ACTIVE = "active";
    public static final String INACTIVE = "inactive";
    public static final String ACTIVATING = "activating";
    public static final String DEACTIVATING = "deactivating";
    public static final String PURGED = "purged";
    public static final String PURGING = "purging";
    public static final String REMOVING = "removing";
    public static final String REQUESTED = "requested";
    public static final String UPDATING_ACTIVE = "updating-active";
    public static final String REMOVED = "removed";
    public static final String UPDATING_INACTIVE = "updating-inactive";
    public static final String RESTORING = "restoring";
```

So we need to map these states to integers, and can list all of them separately, or try to combine them into something simpler. My worry if we combine them is that we are losing information that may not seem important in our use case but that others may be particularly interested in. My preference would be, if we are going to complicate it, just go all the way and show every possible state, and then boil things down in Grafana.

**Comment by Rucknar** [comment]
Agree @JamesBarwell 
Let's not take what we deem useful, let's go for all of it. 
Some of the above i guess isn't applicable to every type of object we query, for instance 'purged' isn't a valid state for a service, only a container. 

Should we trim the container states out and then do all the rest?
```
    public static final String PURGED = "purged";
    public static final String PURGING = "purging";
    public static final String REMOVED = "removed";
```
Can't see any of them being used for anything but a service?

**Comment by jmatsushita** [comment]
+1 one for this. I was looking at a zero from Prometheus wondering what was going on since my service was up, and it turned out it was in `Upgraded` state.

**Comment by Rucknar** [comment]
Implemented in master, pull down `07` from the Docker Hub if you wish to try it out.
