### ISSUE TITLE
Problem with middle dashes and underscores

### ISSUE THREAD

**Issue by jmatsushita** [infinityworksltd/prometheus-rancher-exporter#5]
My services in Rancher (both UI and API) show up with proper `my-very_service` but when returned by this exporter all middle dashes have been converted to lower dashes.

**Comment by Rucknar** [comment]
@JamesBarwell Any chance you could provide some feedback, afaik... this is by design.

**Comment by JamesBarwell** [comment]
Yes, this is by design. Prometheus forbirds dashes, and will fail to parse if it sees one.

See: https://prometheus.io/docs/instrumenting/writing_exporters/

> Only [a-zA-Z0-9:_] are valid in metric names, any other characters should be sanitized to an underscore.
