### ISSUE TITLE
incorrect cattle config url environment variable

### ISSUE THREAD

**Issue by olivierba** [infinityworksltd/prometheus-rancher-exporter#6]
Hi,

Tested with Rancher 1.1.3.  It seems prometheus-rancher-exporter is expecting the environment variable CATTLE_CONFIG_URL while Rancher populate the env variable CATTLE_URL instead

See doc available here http://docs.rancher.com/rancher/v1.0/en/rancher-services/service-accounts/

**Comment by Rucknar** [comment]
Good spot, thanks for reporting. I've not used 1.1.3 yet. Open to a pull-request if you fancy, if not i'll try get a fix up this weekend.

**Comment by olivierba** [comment]
Hi fixed in PR #7 
Can you update the Rancher catalog entry to use it?
Thx

**Comment by Rucknar** [comment]
@olivierba I've merged and pushed the updated container as version '05'. 
I've updated the catalog too, any chance you could give a test? i'm on the road right now without access to an instance. 

Just needs the catalog: https://github.com/Rucknar/community-catalog.git adding into rancher to test. If that looks good, i'll submit a merge request to the community repo.

**Comment by olivierba** [comment]
Hi,

I'll give it a shot before the end of the week

**Comment by olivierba** [comment]
arf, there's a bug in the function checking if env vars are present. Forgot to rename it there. Fixing...

**Comment by olivierba** [comment]
fixed in PR#8
tested in https://github.com/olivierba/community-catalog with rancher 1.1.13 now works ok
