### ISSUE TITLE
TypeError on json.data in app.js

### ISSUE THREAD

**Issue by kuzhao** [infinityworksltd/prometheus-rancher-exporter#9]
Just discovered this when lauching prometheus rancher catalog:
> prometheus-rancher-exporter@0.1.0 start /app
> node app.js

  re listening on 9010 +0ms
  re requesting metrics +3ms
/app/app.js:122
                debug.log('got json results %o', json.data)
                                                     ^

TypeError: Cannot read property 'data' of undefined
    at /app/app.js:122:54
    at Request._callback (/app/app.js:245:20)
    at self.callback (/app/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/app/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)

**Comment by kuzhao** [comment]
Followed by a series of npm error:
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! prometheus-rancher-exporter@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prometheus-rancher-exporter@0.1.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the prometheus-rancher-exporter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls prometheus-rancher-exporter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by Rucknar** [comment]
Thanks for the heads up @kuzhao Could you please provide some information on the setup your using? Ideally:

- Config you're using to run the exporter (all of it, compose or the run command)
- Version of the image you've got running
- Version of Rancher you are using.

**Comment by kuzhao** [comment]
Thanks @Rucknar . Pls refer to the info below:
* docker compose yml
prometheus-rancher-exporter:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: infinityworks/prometheus-rancher-exporter:04
* You can check image version in the compose above
* Rancher 1.1.4

**Comment by Rucknar** [comment]
We had some issues with 04, could you try 05 quickly? if it's still erroring then i'll take a look today.

**Comment by kuzhao** [comment]
> prometheus-rancher-exporter@0.1.1 start /app
> node app.js

/app/app.js:37
            throw new Error('Missing environment variable for option: ' + name)
            ^

Error: Missing environment variable for option: CATTLE_URL
    at /app/app.js:37:19
    at Array.forEach (native)
    at getOptions (/app/app.js:35:18)
    at Object.<anonymous> (/app/app.js:15:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! prometheus-rancher-exporter@0.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prometheus-rancher-exporter@0.1.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the prometheus-rancher-exporter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls prometheus-rancher-exporter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by Rucknar** [comment]
Ah, so the `CATTLE_URL` changed in a recent rancher release, this might be a result of a mis-match. Let me do a little debugging, i think we might of made a mistake with matching the catalog versions up here to the rancher versions. I'll look to make the code backwards compatible today and push an update.

**Comment by kuzhao** [comment]
@Rucknar Glad to know the root cause has been found.
Looking forward to the fixed version

**Comment by Rucknar** [comment]
@kuzhao I've just pushed up version 06 of the docker image. I've not currently got access to an environment to test, would you be so kind to do the honours? I've built from a seperate branch, if it looks good i'll merge. I've set the code to look out for CATTLE_CONFIG_URL and set CATTLE_URL from it if it's detected.

**Comment by kuzhao** [comment]
Honor acknowledge but no luck:
> prometheus-rancher-exporter@0.1.1 start /app
> node app.js

Setting CATTLE_URL from CATTLE_CONFIG_URL
process.env CATTLE_URL process.env.CATTLE_CONFIG_URL
  re listening on 9010 +0ms
  re requesting metrics +3ms
/app/app.js:132
                if((typeof json.data !== 'undefined' && json.data !== null)){
                               ^

TypeError: Cannot read property 'data' of undefined
    at /app/app.js:132:32
    at Request._callback (/app/app.js:257:20)
    at self.callback (/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.init (/app/node_modules/request/request.js:274:17)
    at new Request (/app/node_modules/request/request.js:128:8)
    at request (/app/node_modules/request/index.js:54:10)
    at jsonRequest (/app/app.js:244:5)
    at /app/app.js:131:13

npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! prometheus-rancher-exporter@0.1.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prometheus-rancher-exporter@0.1.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the prometheus-rancher-exporter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls prometheus-rancher-exporter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by Rucknar** [comment]
@kuzhao Right, i've got a 1.14 instance span up to test this. Oddly, i am getting the `CATTLE_URL` set. I need to understand why in your instance this variable isn't set. Please could you run the below, once it's online then execute a shell into the container and type `env`. I'd like to see the output before i proceed. 

```
prometheus-rancher-exporter:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  tty: true
  command:
  - sleep
  - '5000'
  image: infinityworks/prometheus-rancher-exporter:05
  stdin_open: true
```

Ignore the version 6 container i made earlier, upon further reading the fix i attempted isn't suitable.

**Comment by kuzhao** [comment]
/app # env
DEBUG=re
HOSTNAME=8a746252468f
SHLVL=1
HOME=/root
CATTLE_CONFIG_URL=http://atomic-master:8080/v1
CATTLE_SECRET_KEY=myxqTwXa9p8BUJoWjGnA5NrvpgxBWFHYfxgM69LF
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CATTLE_URL=http://atomic-master:8080/v1
CATTLE_AGENT_INSTANCE_AUTH=Basic QjUxMzY4NjJCQjhEQUM4M0ExMjE6bXl4cVR3WGE5cDhCVUpvV2pHbkE1TnJ2cGd4QldGSFlmeGdNNjlMRg==
PWD=/app
CATTLE_ACCESS_KEY=B5136862BB8DAC83A121

**Comment by wzrdtales** [comment]
@Rucknar I do encounter the same problem.

# My environment 

rancher-v1.2.0-rc1

```
docker info
Containers: 21
 Running: 15
 Paused: 0
 Stopped: 6
Images: 28
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-101-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.767 GiB
Name: tobidev
ID: LR5X:UG57:LSOJ:7ILT:SC2A:N32Q:4QPD:M2FZ:PQGD:CN2X:6LZN:FVFK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

# The Error

```
> prometheus-rancher-exporter@0.1.1 start /app
> node app.js

/app/app.js:37
            throw new Error('Missing environment variable for option: ' + name)
            ^

Error: Missing environment variable for option: CATTLE_URL
    at /app/app.js:37:19
    at Array.forEach (native)
    at getOptions (/app/app.js:35:18)
    at Object.<anonymous> (/app/app.js:15:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

**Comment by wzrdtales** [comment]
Strange enough, from inside the container I do get:

```
# echo $CATTLE_URL
http://myhost:8080/v1
```

it actually is not missing though.

**Comment by wzrdtales** [comment]
When I use the `latest` instead of the `05` tag I do run into this error instead:

```
/app/app.js:115
    return name.replace(/[^a-zA-Z0-9_:]/g, '_')
               ^

TypeError: Cannot read property 'replace' of undefined
    at getSafeName (/app/app.js:115:16)
    at /app/app.js:91:31
    at Array.map (native)
    at /app/app.js:88:25
    at /app/app.js:226:9
    at /app/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/app/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by wzrdtales** [comment]
I builded up my own container, and now I see it fails over here, when the environment seems to be not defined at all:

https://github.com/infinityworksltd/prometheus-rancher-exporter/blob/master/app.js#L91

**Comment by wzrdtales** [comment]
I modified the line 91, https://github.com/infinityworksltd/prometheus-rancher-exporter/blob/master/app.js#L91, now and after that it is working for me.

I modified the name to always be a string, not the cleanest solution but enough as a quick workaround:

    (''+name)

I assume that on the latest rancher something has changed that you will need to adjust?

**Comment by kuzhao** [comment]
My rancher version is the latest 1.1.4 stable. 
Pardon me for having no knowledge upon javascript. @wzrdtales so it could be an issue of inproper var type?

**Comment by wzrdtales** [comment]
@kuzhao The lines that I posted do fix stuff for the second error I posted. That is different from the CATTLE_URL stuff. And no there is no such thing as improper var type though, the problem was for rancher-v1.2.0-rc4 that there seems to be big changes on the environment information. There are actually services now that run as "infrastructure" stack, which this module got wrong and did not get an environment at all, which caused the second error.

However I think that this module needs an update for rancher-1.2.0 as there are also not all stats visible in the dashboard.

As you're on the 1.1.4 branch you may just try the :latest tag instead, which seems to be the last really working version, except for rancher-1.2.0 which has the mentioned error. You can try may workaround also if you want if it works for you `wzrdtales/prometheus-rancher-exporter:latest`, but can't tell you if it is going to work for you though.

**Comment by kuzhao** [comment]
@wzrdtales all right, will try both and thank you for the fix>
Anyway, as v1.2 is on the way this catalog will need some tuning to fit the new rancher.

**Comment by Rucknar** [comment]
All - 1.2 rancher does indeed not work with the existing version. I've created a bug to track it and i've got a build in dev now that should resolve. (https://github.com/infinityworksltd/prometheus-rancher-exporter/issues/11)

Regarding the above issue, i think this might of stemmed from a pull request we put in before without adequate testing. I'm looking at adding proper unit test coverage now. @wzrdtales do you fancy putting in a pull request for the fix you've got? @kuzhao did that work for you?

**Comment by kuzhao** [comment]
@Rucknar As my department's advancing with rancher v1.2 I've got no chance of tryout at present. 
I will setup a private env and do a test then once the fix has been merged.

**Comment by wzrdtales** [comment]
@Rucknar Can do this, did not think this would be worth merging as I really just edited a single line to have a workaround. Putting up a PR for you though in a few minutes/hours though :)

**Comment by Rucknar** [comment]
FYI... Just posted this in the 1.2 ticket. If anyone fancies helping test the re-write...

Branch pushed (rewrite) https://github.com/infinityworksltd/prometheus-rancher-exporter/tree/rewrite

Image available here: infinityworks/prometheus-rancher-exporter:go-rewrite

You can run locally with:

docker run -d -e CATTLE_ACCESS_KEY="XXXXXXXX" -e CATTLE_SECRET_KEY="XXXXXXX" -e CATTLE_URL="http://<YOUR_IP>:8080/v2-beta/" -p 9010:9010 infinityworks/prometheus-rancher-exporter:go-rewrite

Thoughts / Feedback welcome. The metrics for health are way more detailed now. I'll get some example queries up tomorrow and work on the docs tomorrow afternoon.

**Comment by Rucknar** [comment]
@kuzhao @wzrdtales I've just pushed an updated exporter. It's been predominantly tested on Rancher 1.2, though i'm hopeful that it's backwards compatible. Do you fancy giving it a shot?

Beta version is available at `infinityworks/prometheus-rancher-exporter:rewrite`

**Comment by Rucknar** [comment]
And now merged to master, pushed up version `07` which will be put into an updated Rancher community catalog entry hopefully tomorrow.

**Comment by wzrdtales** [comment]
@Rucknar Sure will do, was just busy the last few days moving to a new accomodation :)

**Comment by kuzhao** [comment]
@Rucknar Got it. Will test then as soon as the catalog has been updated.

**Comment by Rucknar** [comment]
Thanks all, 

I ran the output of the metrics by one of the Prometheus core engineers, they correctly pointed out the correct way to get the 'state' dimension is through labels. I've updated the code and pushed. Apologies if anyone's already built some queries against the metric names i pushed yesterday. Hopefully these will now stay stable. On the plus side, it's now much easier and faster to correctly query the data from tools like Grafana.

I'll hold the ticket open until the community update is merged into Rancher.

**Comment by Rucknar** [comment]
@kuzhao Catalog update has been merged. The updates catalog entry requires 1.2 or greater due to some changes around cadvisor (rancher no longer ships by default). If you choose to upgrade, remember you may lost any data/graphs, backup anything you wish to keep.

**Comment by Rucknar** [comment]
@kuzhao Given the error relates directly to the nodejs implementation, which has been re-written. I'm going to close this one down, if you hit any issues... please create a new issue, otherwise it might become a bit confusing having it all in this ticket.

Thanks

**Comment by kuzhao** [comment]
@Rucknar Of course:) As some work related stuff got hot recently I didn't manage to tap this issue. Anyway, glad to catch your attention on this and for the resolution.
